library(xaringan)

inf_mr("Statistik_II_1_SS24.Rmd")
inf_mr("Statistik_II_2_SS24.Rmd")
inf_mr("Statistik_II_3_SS24.Rmd")
inf_mr("Statistik_II_4_SS24.Rmd")
inf_mr("Statistik_II_5_SS24.Rmd")
inf_mr("Statistik_II_6_SS24.Rmd")
inf_mr("Statistik_II_7_SS24.Rmd")
inf_mr("Statistik_II_8_SS24.Rmd")
inf_mr("Statistik_II_9_SS24.Rmd")
inf_mr("Statistik_II_10_SS24.Rmd")
inf_mr("Statistik_II_11_SS24.Rmd")
inf_mr("Statistik_II_12_SS24.Rmd")
